# Generated by Django 4.2 on 2023-05-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(max_length=64, verbose_name="Job")),
                ("job_description", models.TextField()),
                ("published_date", models.DateTimeField(auto_now_add=True)),
                (
                    "dead_line",
                    models.DateTimeField(
                        choices=[("7 days", 7), ("14 days", 14), ("30 days", 30)],
                        max_length=64,
                    ),
                ),
                (
                    "seeker_level",
                    models.CharField(
                        choices=[
                            ("Internship", "Internship"),
                            ("Junior", "Junior"),
                            ("Middle", "Middle"),
                            ("Senior", "Senior"),
                        ],
                        default="Undefined",
                        max_length=64,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True, default="Undefined", max_length=64, null=True
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        choices=[
                            ("full", "Full Time"),
                            ("remote", "Remote"),
                            ("contract", "Contract"),
                            ("part", "Part time"),
                        ],
                        default="Permanent",
                        max_length=64,
                    ),
                ),
            ],
        ),
    ]
