# Generated by Django 4.2 on 2023-05-01 07:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import services.image_services


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("job", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "company_name",
                    models.CharField(max_length=64, verbose_name="Company name"),
                ),
                ("industry", models.CharField(max_length=128, verbose_name="Industry")),
                (
                    "date_of_foundation",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "number_of_employees",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        max_length=256,
                        null=True,
                        verbose_name="Company Location",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        max_length=2048,
                        null=True,
                        verbose_name="About this company",
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(blank=True, max_length=32, null=True),
                ),
                (
                    "company_icon",
                    models.ImageField(
                        default="company.ico",
                        upload_to=services.image_services.get_path_upload_avatar_company,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=["jpg", "png", "jpeg", "bmp", "ico"]
                            ),
                            services.image_services.validate_profile_image_size,
                        ],
                    ),
                ),
                (
                    "active_jobs",
                    models.ManyToManyField(
                        blank=True, default=None, null=True, to="job.job"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
