# Generated by Django 4.2 on 2023-04-11 14:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import services.image_services


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('location', models.CharField(blank=True, max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Seeker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=16)),
                ('citizen', models.CharField(blank=True, max_length=64, null=True)),
                ('skills', models.TextField()),
                ('first_login', models.DateTimeField(blank=True, null=True)),
                ('languages', models.TextField()),
                ('github_acc', models.URLField(blank=True, null=True)),
                ('linkedin_acc', models.URLField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female')], default='male', max_length=6)),
                ('hobbies', models.TextField(blank=True, null=True)),
                ('about', models.TextField(blank=True, max_length=2048, null=True)),
                ('profile_image', models.ImageField(default='user_image_def.jpg', upload_to=services.image_services.get_path_upload_avatar_user, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'bmp']), services.image_services.validate_profile_image_size])),
                ('education', models.ManyToManyField(blank=True, default=1, null=True, related_name='seekers', to='seeker.university')),
                ('user', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='seeker', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
