# Generated by Django 4.2 on 2023-05-01 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("job", "0001_initial"),
        ("seeker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="seeker",
            name="applied_jobs",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="job.job",
            ),
        ),
    ]
